// Abilities learned in the Survival Log with Planning Points (sources: talent guide G6, patch notes
// 08-13 … 09-12). Each level applies `per` once more. Abilities persist across loops; points spent in
// the current round are refunded by "Tear Up This Round and Rewrite".
export const ABILITIES = [
  {
    id: 'quickRest',
    name: { en: 'Quick Rest', zh: '快速休整' },
    desc: { en: 'Resting and sleeping restore 20% more Stamina per level.', zh: '每级：休息恢复精力的速度加快20%。' },
    maxLv: 3,
    cost: [40, 80, 140],
    per: { restGain: 0.2 },
  },
  {
    id: 'efficientEating',
    name: { en: 'Efficient Eating', zh: '高效饮食' },
    desc: { en: '+15% Satiety from food per level.', zh: '每级：进食获得的饱腹度+15%。' },
    maxLv: 3,
    cost: [40, 80, 140],
    per: { eatSat: 0.15 },
  },
  {
    id: 'emotionalManagement',
    name: { en: 'Emotional Management', zh: '情绪管理' },
    desc: { en: 'Morale drops 10% slower per level.', zh: '每级：心态的下降速度减慢10%。' },
    maxLv: 3,
    cost: [40, 80, 140],
    per: { morDecay: -0.1 },
  },
  {
    id: 'energySavingMetabolism',
    name: { en: 'Energy-Saving Metabolism', zh: '节能代谢' },
    desc: { en: 'Satiety drops 10% slower per level.', zh: '每级：饱腹度的下降速度减慢10%。' },
    maxLv: 3,
    cost: [40, 80, 140],
    per: { satDecay: -0.1 },
  },
  {
    id: 'psychologicalConstruction',
    name: { en: 'Psychological Construction', zh: '心理建设' },
    desc: { en: '+15 max Morale per level.', zh: '每级：心态上限+15。' },
    maxLv: 3,
    cost: [50, 100, 160],
    per: { maxAdd: { mor: 15 } },
  },
  {
    id: 'effortSaving',
    name: { en: 'Effort-Saving Tricks', zh: '省力诀窍' },
    desc: { en: 'Actions cost 10% less Stamina per level.', zh: '每级：精力消耗-10%。' },
    maxLv: 3,
    cost: [50, 100, 160],
    per: { staCost: -0.1 },
  },
  {
    id: 'heartyMeal',
    name: { en: 'Hearty Meal Training', zh: '饱餐锻炼' },
    desc: { en: '+15 max Satiety per level.', zh: '每级：饱腹度上限+15。' },
    maxLv: 3,
    cost: [50, 100, 160],
    per: { maxAdd: { sat: 15 } },
  },
  {
    id: 'energyManagement',
    name: { en: 'Energy Management', zh: '精力管理' },
    desc: { en: 'Night sleep restores 50% more Stamina; daytime sleep 50% less.', zh: '白天睡觉恢复的精力-50%，夜间睡觉恢复的精力+50%。' },
    maxLv: 1,
    cost: [80],
    per: { sleepNight: 0.5, sleepDay: -0.5 },
  },
  {
    id: 'thrifty',
    name: { en: 'Thrifty', zh: '精打细算' },
    desc: { en: 'Planning cards at the daily settlement cost 15% less.', zh: '结算时购买奖励选项可享受8.5折。' },
    maxLv: 1,
    cost: [120],
    per: { settlementDiscount: 0.15 },
  },
  {
    id: 'dailyPlan',
    name: { en: 'Daily Settlement Plan', zh: '日结计划' },
    desc: { en: '+1 Planning Point at every daily settlement per level.', zh: '每级：每日结算时获得的生存点增加1点。' },
    maxLv: 5,
    cost: [60, 90, 120, 160, 200],
    per: { pointsPerDay: 1 },
  },
  {
    id: 'bulkBargains',
    name: { en: 'Bulk Bargains', zh: '批量优惠' },
    desc: { en: 'Bulk packages before the disaster are 8% cheaper per level.', zh: '每级：灾前购买大包装商品便宜8%。' },
    maxLv: 5,
    cost: [30, 60, 90, 120, 160],
    per: { bulkDiscount: 0.08 },
  },
  {
    id: 'broadShoulders',
    name: { en: 'Broad Shoulders', zh: '宽肩膀' },
    desc: { en: '+5 kg carry capacity per level.', zh: '每级：负重上限+5千克。' },
    maxLv: 4,
    cost: [40, 80, 120, 180],
    per: { carryKg: 5 },
  },
  {
    id: 'savings',
    name: { en: 'Savings', zh: '储蓄' },
    desc: { en: '+$150 starting money per level.', zh: '每级：灾前初始资金+150。' },
    maxLv: 4,
    cost: [50, 100, 150, 220],
    per: { startMoney: 150 },
  },
  {
    id: 'earlyBird',
    name: { en: 'Early Warning', zh: '先知先觉' },
    desc: { en: '+30 minutes of preparation time before the outbreak per level.', zh: '每级：灾前准备时间+30分钟。' },
    maxLv: 4,
    cost: [60, 120, 180, 260],
    per: { prepHours: 0.5 },
  },
  {
    id: 'lightSleeper',
    name: { en: 'Light Sleeper', zh: '浅眠' },
    desc: { en: 'Wake up automatically when zombies attack; sleep needs 20% less time.', zh: '丧尸来袭时自动醒来；睡眠所需时间-20%。' },
    maxLv: 1,
    cost: [80],
    per: { lightSleeper: 1 },
  },
  {
    id: 'energyStorage',
    name: { en: 'Energy Storage', zh: '储能' },
    desc: { en: '+20% battery capacity per level.', zh: '每级：蓄电容量+20%。' },
    maxLv: 3,
    cost: [60, 110, 170],
    per: { batteryMult: 0.2 },
  },
  {
    id: 'deepFreezing',
    name: { en: 'Deep Freezing', zh: '深度冷冻' },
    desc: { en: 'Fridges and freezers preserve food 20% better per level.', zh: '每级：冰箱冰柜保鲜效果提升20%。' },
    maxLv: 3,
    cost: [50, 100, 150],
    per: { fridgeMult: -0.2 },
  },
  {
    id: 'properRefrigeration',
    name: { en: 'Proper Refrigeration', zh: '妥善冷藏' },
    desc: { en: 'Food outside the fridge spoils 15% slower per level.', zh: '每级：冰箱外的食物腐坏速度减慢15%。' },
    maxLv: 2,
    cost: [60, 120],
    per: { roomSpoil: -0.15 },
  },
  {
    id: 'mentalToughness',
    name: { en: 'Mental Toughness', zh: '心理韧性' },
    desc: { en: 'Unlocks a once-per-day button that restores 30 Morale.', zh: '解锁每天一次的按钮：立即恢复30点心态。' },
    maxLv: 1,
    cost: [70],
    per: { mentalToughness: 1 },
  },
  {
    id: 'handyman',
    name: { en: 'Handyman', zh: '巧手' },
    desc: { en: '+10% chance of Perfect crafting per level.', zh: '每级：完美制造概率+10%。' },
    maxLv: 2,
    cost: [80, 160],
    per: { craftPerfect: 0.1 },
  },
  {
    id: 'greenFingers',
    name: { en: 'Green Fingers', zh: '园艺天分' },
    desc: { en: 'Crops grow 10% faster and yield more per level.', zh: '每级：作物生长速度+10%，产量提升。' },
    maxLv: 2,
    cost: [80, 160],
    per: { growMult: 0.1, plantYield: 0.15 },
  },
  {
    id: 'homeChef',
    name: { en: 'Home Chef', zh: '家常大厨' },
    desc: { en: 'Cooking quality rolls +8% per level.', zh: '每级：烹饪品质判定+8%。' },
    maxLv: 2,
    cost: [80, 160],
    per: { cookQuality: 8 },
  },
  {
    id: 'fortifier',
    name: { en: 'Fortifier', zh: '加固专家' },
    desc: { en: 'Door and window repairs restore 25% more durability per level.', zh: '每级：修补门窗恢复的耐久+25%。' },
    maxLv: 2,
    cost: [80, 160],
    per: { repairMult: 0.25 },
  },
  {
    id: 'scavenger',
    name: { en: 'Scavenger', zh: '拾荒老手' },
    desc: { en: 'Searching containers is 20% faster and finds more per level.', zh: '每级：搜索速度+20%，找到更多物资。' },
    maxLv: 2,
    cost: [80, 160],
    per: { searchSpeed: 0.2, lootMult: 0.15 },
  },
];

export const ABILITY_BY_ID = Object.fromEntries(ABILITIES.map((a) => [a.id, a]));
