// Post-disaster exploration points (dev logs #3/#4/#6, patches 08-14 … 09-12, guides G1/G2/G3).
// Six sites with unlock days, opening hours, danger, darkness, loot richness, travel time and a
// hand-authored iso map each. Config_Furniture ships the scene props (shelves, the overturned truck,
// electrical boxes, fire cabinets…) with loot *group* ids but no loot tables, so the tables below are
// built from item categories.
//
// Map legend: '#' wall, 'D' entrance (outer wall), 'W' window, '.' floor, ',' road, ':' sidewalk,
// 'z' floor + zombie spawn point. Any other character is a fixture from the site legend; its w×h
// footprint is drawn with the same character (scanned left-to-right, top-to-bottom).
// Fixture kinds: box (searchable container), block (obstacle to push away), rest (bed / sofa), scrap (junk taken apart
// for its materials), prop (stands there, nothing to do with it).
// lock: 'pry' needs a crowbar, 'pick' takes a lockpick (or a crowbar, noisily). Both tools break.
import { item } from '../data/db.js';
import { withWing } from './siteWings.js';

export const ITEM = { crowbar: 20330, lockpick: 20320, recorder: 9049, wmNote: 9014, teachingDrone: 9044 };
export const HOSPITAL_CLUES = [9041, 9042, 9043];
export const TRUTH_CLUES = [...HOSPITAL_CLUES, 9062];
// The College Student's own finds in the hospital; each fills the slot of the record it pairs with (CLUES).
export const STUDENT_COPIES = [9063, 9064];
export const RATION_PRESS_RECIPE = 416;

// Item pools (Config_Item ids).
const RAW_POOLS = {
  staple: [2102, 2105, 2106, 2107, 2108, 2161, 2902, 2910, 2911, 2912, 9030],
  canned: [2115, 2123, 2149, 9030, 9031],
  meatDry: [2112, 2114, 2120, 2128, 2904, 2907],
  dairy: [2117, 2119, 2121],
  vegDry: [2124, 2129, 2905],
  fresh: [2125, 2127, 2502, 2503, 2504, 2522, 2527, 2528, 2530, 2531, 2533, 2536, 2538],
  snack: [2132, 2133, 2134, 2135, 2138, 2139, 2141, 2143, 2903, 2909, 9032],
  seasoning: [2144, 2145, 2146, 2148, 2150, 2151, 2153, 2154, 2155, 2163],
  drink: [2130, 2131, 2136, 2142],
  liquor: [2137, 2156, 2157, 2158, 2159],
  medicine: [2147, 2400, 2402, 2404, 2406, 2407, 2408, 2409, 2410, 2411, 2509, 2509],
  medicineRare: [2401, 2403, 2405, 2412],
  spray: [2164, 2165, 2166],
  scrap: [20001, 20002, 20003, 20004, 20005, 20105],
  material: [20101, 20102, 20103, 20104, 20106, 20107],
  materialRare: [20210, 20214, 20300, 20301, 20310, 20311, 20312, 20360, 20361, 20362],
  electronic: [20210, 20104, 20104],
  fuel: [8001, 15504, 15505, 15506, 40000],
  tool: [20320, 20340, 20350],
  toolRare: [20330, 20320, 20350],
  book: [2505, 2506, 3001, 3002, 3003, 3004, 3006, 3022, 3023, 3024, 3025, 3026],
  note: [3015, 3027, 3028, 3029, 3030, 3031, 3032],
  seed: Array.from({ length: 34 }, (_, i) => 15007 + i),
  fertilizer: [15501, 15502, 15503],
  trap: [25001, 25003, 25004],
  bait: [26008, 26008, 26009, 26010],
  molotov: [26005, 26006, 26007],
  daily: [2508, 11006, 11009, 11010, 11011, 11012, 11013],
  valuable: [31001, 11014, 11015, 11016, 11017, 11018, 11019, 11020, 11021, 11022],
  console: [5, 11002],
};

export const LOOT_POOLS = Object.fromEntries(Object.entries(RAW_POOLS).map(([k, ids]) => [k, ids.filter((id) => item(id))]));

// Fresh produce only turns up during the first days after the outbreak.
export const FRESH_DAYS = 8;

// Container loot tables: [pool, weight].
export const LOOT_TABLES = {
  grocery: [['staple', 4], ['canned', 2], ['snack', 3], ['drink', 2], ['seasoning', 2], ['meatDry', 1.5], ['dairy', 0.5], ['vegDry', 0.5], ['liquor', 0.4], ['fresh', 0.6]],
  freezer: [['bait', 5], ['canned', 1], ['meatDry', 1]],
  fridge: [['bait', 2], ['dairy', 2], ['drink', 2], ['canned', 1], ['fresh', 1]],
  checkout: [['snack', 4], ['drink', 2], ['daily', 2], ['book', 1], ['scrap', 1]],
  stockroom: [['staple', 2], ['canned', 2], ['drink', 2], ['scrap', 2], ['material', 1]],
  truck: [['staple', 3], ['canned', 3], ['drink', 2], ['meatDry', 1], ['material', 1]],
  grill: [['fuel', 3], ['meatDry', 1], ['scrap', 1]],
  hardware: [['material', 3], ['scrap', 2], ['trap', 1], ['fuel', 1], ['tool', 0.6], ['daily', 0.4]],
  toolShelf: [['material', 3], ['scrap', 2], ['tool', 1], ['trap', 1], ['fuel', 0.5]],
  materials: [['scrap', 4], ['material', 3], ['materialRare', 0.6]],
  toolCabinet: [['tool', 2], ['material', 3], ['materialRare', 1], ['scrap', 1]],
  garden: [['seed', 5], ['fertilizer', 2], ['trap', 0.5]],
  fuelDrum: [['fuel', 5]],
  raider: [['canned', 2], ['medicine', 2], ['snack', 1], ['material', 1], ['fuel', 1], ['tool', 0.4], ['medicineRare', 0.3]],
  medicine: [['medicine', 6], ['spray', 1], ['medicineRare', 0.4]],
  sealedMeds: [['medicine', 3], ['medicineRare', 3]],
  nurse: [['medicine', 4], ['spray', 1], ['book', 0.5], ['daily', 0.5]],
  lab: [['medicine', 2], ['spray', 1], ['material', 1], ['fuel', 1]],
  medFridge: [['medicineRare', 2], ['medicine', 3], ['bait', 1]],
  medWaste: [['scrap', 2], ['medicine', 1], ['material', 1]],
  electrical: [['electronic', 5], ['scrap', 1], ['materialRare', 0.5]],
  generator: [['fuel', 4], ['electronic', 1], ['scrap', 1]],
  desk: [['book', 2], ['snack', 2], ['daily', 1], ['scrap', 1], ['note', 0.3]],
  locker: [['snack', 2], ['daily', 2], ['book', 1], ['drink', 1], ['medicine', 0.4], ['console', 0.08]],
  bookcase: [['book', 4], ['note', 1.5]],
  canteen: [['staple', 2], ['canned', 1], ['dairy', 1], ['seasoning', 2], ['drink', 1], ['fresh', 0.5]],
  tuckshop: [['snack', 5], ['drink', 3]],
  vending: [['snack', 3], ['drink', 4]],
  sundries: [['daily', 4], ['snack', 1], ['drink', 1]],
  breakroom: [['snack', 2], ['drink', 2], ['daily', 1], ['seasoning', 1]],
  safe: [['valuable', 2], ['medicineRare', 1.5], ['toolRare', 1], ['molotov', 0.5], ['console', 0.5], ['note', 1]],
  fireCabinet: [['toolRare', 2], ['materialRare', 1], ['material', 1]],
  filing: [['note', 2], ['book', 1], ['scrap', 2]],
  office: [['scrap', 3], ['material', 1], ['daily', 1], ['snack', 0.5]],
  trash: [['scrap', 3], ['staple', 1], ['snack', 1], ['bait', 0.3]],
  camp: [['staple', 2], ['canned', 1], ['medicine', 1], ['daily', 1], ['fuel', 1]],
  bag: [['staple', 2], ['snack', 1], ['drink', 1], ['medicine', 1], ['book', 0.5], ['tool', 0.3]],
  car: [['fuel', 2], ['scrap', 2], ['material', 1], ['medicine', 0.5], ['tool', 0.4]],
  plant: [['seed', 3], ['fertilizer', 1]],
  newspaper: [['book', 3], ['scrap', 1]],
  gym: [['daily', 2], ['drink', 2], ['snack', 1]],
  // extra rolls from a hidden stash (the Warehouse Manager spots these at a glance)
  stash: [['medicineRare', 2], ['toolRare', 1], ['materialRare', 2], ['fuel', 1], ['canned', 2], ['molotov', 0.5], ['valuable', 0.5]],
};

const box = (cfg, loot, rolls = 2, extra = {}) => ({ kind: 'box', cfg, loot, rolls, w: 1, h: 1, ...extra });
const wide = (cfg, loot, rolls = 2, extra = {}) => box(cfg, loot, rolls, { w: 2, ...extra });
const block = (cfg) => ({ kind: 'block', cfg, w: 1, h: 1 });
const rest = (cfg, w = 2) => ({ kind: 'rest', cfg, w, h: 1 });

// Search time (game minutes) by footprint and extra minutes for locks. The config gives no duration (the FuncAction
// table is not in src/data/gen); these are a third of the first guesses (12-30, locks +10/+15), which read as a stall
// in play (owner playtest, 2026-09-26): a site's day is a few hours, and a search should cost minutes of it, not half
// an hour. Loose finds (拾取) and a shop's loot spots take 2.
export const SEARCH_MIN = { 1: 4, 2: 6, 4: 8, 6: 10 };
export const LOCK_EXTRA_MIN = { pry: 5, pick: 3 };
export const CLEAR_MIN = 40;
export const REST_MIN = 60;

// Each site's map is widened by a wing that places the rest of its scene's config pieces (src/content/siteWings.js).
export const SITES = [
  {
    id: 'streets',
    icon: '🏘',
    name: { en: 'Nearby Streets', zh: '附近街区' },
    desc: {
      en: 'The block around your building: burnt-out cars, a looted corner shop and whatever the neighbors dropped while running. Close, small and picked over.',
      zh: '楼下的街区：烧毁的汽车、被洗劫过的街角小店，还有邻居们逃命时丢下的东西。离家近、规模小，早被翻过一遍了。',
    },
    size: 'small',
    tier: 1,
    unlockDay: 1,
    hours: [6, 20],
    danger: 0.7,
    dark: false,
    outdoor: true,
    richness: 0.75,
    travelMin: 30,
    zombies: 2,
    bigChance: 0,
    mapPos: [0.42, 0.64],
    map: [
      '##################',
      '#::::::::#.KK..SS#',
      '#:T::::::#.......#',
      '#::::::::W..B..SS#',
      '#:::::::::.....z.#',
      '#:P::::::#########',
      '#,,,,,,,,,,,,,,,,#',
      '#,,VV,,,,,,,,CC,,#',
      '#,,VV,,,,,,z,CC,,#',
      '#,,,,,,,,,,,,,,,,#',
      '#:::::::::::::O::#',
      '#:NN:::::::::A:::#',
      '#z:::::::::::R:::#',
      '########D#########',
    ],
    legend: {
      K: wide(912, 'checkout'),
      S: wide(884, 'grocery'),
      B: box(913, 'stockroom', 1),
      T: box(66081, 'trash', 1),
      P: box(66100, 'plant', 1),
      V: box(66083, 'car', 2, { w: 2, h: 2 }),
      C: box(67005, 'car', 3, { w: 2, h: 2, lock: 'pry' }),
      O: box(66049, 'fuelDrum', 1),
      N: wide(66067, 'camp'),
      A: box(66192, 'bag'),
      R: box(66059, 'newspaper', 1),
    },
    rooms: [{ id: 'shop', x: 10, y: 1, w: 7, h: 4, label: { en: 'Corner Shop', zh: '街角小店' } }],
  },
  {
    id: 'hardware',
    icon: '🔧',
    name: { en: 'Hardware Store', zh: '五金店' },
    desc: {
      en: 'Tool aisles, lumber and a garden corner. Materials, fuel and seeds; a locked storeroom in the back. Open around the clock.',
      zh: '工具货架、建材和园艺角。能找到材料、燃料和种子，后面还有上锁的储藏间。全天开放。',
    },
    size: 'small',
    tier: 1,
    unlockDay: 3,
    hours: null,
    danger: 0.8,
    dark: false,
    richness: 0.9,
    travelMin: 40,
    zombies: 2,
    bigChance: 0.05,
    mapPos: [0.68, 0.7],
    map: [
      '################',
      '#TT.TT.TT.#KLL.#',
      '#.........#....#',
      '#MM.MM.PP.#.OO.#',
      '#.........#..z.#',
      '#SS.SS.GG.#..XX#',
      '#.........##.###',
      '#..z...........#',
      '#.RR....BB..HH.#',
      '#.............z#',
      '#.YY..........I#',
      '#######D########',
    ],
    legend: {
      T: wide(66039, 'toolShelf'),
      K: box(9120, 'toolCabinet', 2, { lock: 'pry' }),
      L: wide(66048, 'materials'),
      M: wide(389, 'materials'),
      P: wide(66075, 'hardware'),
      O: box(66110, 'fuelDrum', 1),
      S: wide(66035, 'hardware'),
      G: wide(66063, 'garden'),
      X: wide(66150, 'toolCabinet'),
      R: wide(911, 'checkout'),
      B: wide(914, 'stockroom'),
      H: wide(9115, 'toolCabinet', 2, { lock: 'pick' }),
      Y: wide(66061, 'garden'),
      I: box(67060, 'toolCabinet', 3, { lock: 'pry' }),
    },
    rooms: [{ id: 'storeroom', x: 11, y: 1, w: 4, h: 5, label: { en: 'Storeroom', zh: '储藏间' } }],
  },
  {
    id: 'supermarket',
    icon: '🛒',
    name: { en: 'Ruined Supermarket', zh: '残破超市' },
    desc: {
      en: 'Pitch black since the power died — a flashlight beam is all you have. Toppled shelves, dead freezers and an overturned truck at the loading dock. Push for one more shelf?',
      zh: '断电后一片漆黑，只有手电筒的光。倒塌的货架、断电的冰柜，还有卸货区一辆侧翻的货车。再多搜一个货架吗？',
    },
    size: 'medium',
    tier: 2,
    unlockDay: [12, 17],
    hours: null,
    danger: 1,
    dark: true,
    richness: 1.05,
    travelMin: 45,
    zombies: 4,
    bigChance: 0.1,
    mapPos: [0.26, 0.34],
    map: [
      '####################',
      '#TTT...#.QQ..#LL..S#',
      '#TTT.z.#.....#..N..#',
      '#......#.bb..#.....#',
      '###.#######.####.###',
      '#FF.FF......GG..X..#',
      '#.........z........#',
      '#.AAA.HHH..JJJ.KKK.#',
      '#..................#',
      '#.AAA.HHH..JJJ.KKK.#',
      '#....z.........z...#',
      '#..................#',
      '#.CC..CC..CC....QQ.#',
      '#..................#',
      '#..................#',
      '##########D#########',
    ],
    legend: {
      T: box(882, 'truck', 2, { w: 3, h: 2, lock: 'pry', id: 'truck', story: [{ item: ITEM.wmNote, cond: 'student' }] }),
      Q: wide(913, 'stockroom'),
      b: wide(914, 'stockroom'),
      L: wide(66031, 'locker'),
      S: box(66034, 'office', 1),
      N: box(66059, 'newspaper', 1),
      F: wide(908, 'freezer', 2, { lock: 'pry' }),
      G: wide(910, 'grill', 1),
      X: block(897),
      A: box(884, 'grocery', 2, { w: 3 }),
      H: box(888, 'grocery', 2, { w: 3 }),
      J: box(896, 'grocery', 2, { w: 3 }),
      K: box(901, 'grocery', 2, { w: 3 }),
      C: wide(911, 'checkout'),
    },
    rooms: [
      { id: 'dock', x: 1, y: 1, w: 6, h: 3, label: { en: 'Loading Dock', zh: '卸货区' } },
      { id: 'stock', x: 8, y: 1, w: 5, h: 3, label: { en: 'Stockroom', zh: '仓储间' } },
      { id: 'staff', x: 14, y: 1, w: 5, h: 3, label: { en: 'Staff Room', zh: '员工休息室' } },
      { id: 'freezers', x: 1, y: 5, w: 6, h: 1, cold: true, label: { en: 'Frozen Aisle', zh: '冷冻区' } },
    ],
    lore: [9050, 9051, 9052],
    loreIn: ['L', 'S', 'N', 'C', 'Q', 'b'],
  },
  {
    id: 'school',
    icon: '🏫',
    name: { en: 'Abandoned School', zh: '废弃学校' },
    desc: {
      en: 'The largest site: classrooms, a canteen with a tuck shop, the office, infirmary and science lab. Collapsed desks wall off whole wings — working through it takes time and preparation.',
      zh: '最大的探索点：教室、带小卖部的食堂、办公室、医务室和实验室。倒塌的课桌椅堵住了好几片区域，要花时间、做好准备才能深入。',
    },
    size: 'large',
    tier: 3,
    unlockDay: [18, 22],
    hours: [7, 19],
    danger: 1.15,
    dark: false,
    richness: 1.15,
    travelMin: 55,
    zombies: 6,
    bigChance: 0.12,
    mapPos: [0.72, 0.26],
    map: [
      '############################',
      '#FF..BB..#K...MM.#GG.GG..P.#',
      '#..O....S#.RR....#.........#',
      '#........#.......#....z....#',
      '#F.......#....Q..#.......T.#',
      '#........#.......#.........#',
      '####.########.########.#####',
      '#E......z..................#',
      '#############.##############',
      '#.C.C.#.LL..#.#UU.V.NN..H..#',
      '#.....#.....#X#.....z......#',
      '#.C.C.#.Y.Y.#.#.AA..AA.....#',
      '#BB...#..z..#.#........II.k#',
      '#.....#.....#.#...........J#',
      '###.#####.###.######X#######',
      '#...llll..E......p......b..#',
      '#...z...............z......#',
      '#j....t..............nn....#',
      '#..........................#',
      '#############D##############',
    ],
    legend: {
      F: box(67123, 'filing'),
      B: wide(67018, 'bookcase', 3),
      K: box(67194, 'medicine'),
      M: wide(67044, 'nurse'),
      G: wide(67195, 'lab'),
      P: box(67088, 'stockroom', 2, { id: 'droneCrate', story: [{ item: ITEM.teachingDrone, cond: 'studentMidgame' }] }),
      O: box(67199, 'office', 1),
      S: box(67045, 'safe', 1, { lock: 'pick' }),
      R: rest(9122),
      Q: box(67069, 'medicine'),
      T: box(67060, 'toolCabinet', 3, { lock: 'pry' }),
      E: box(67122, 'fireCabinet', 1, { lock: 'pick' }),
      C: box(67049, 'desk'),
      L: wide(67074, 'desk'),
      U: wide(67024, 'fridge'),
      V: box(67025, 'canteen'),
      N: wide(67152, 'canteen'),
      H: box(67155, 'canteen'),
      X: block(67020),
      Y: box(67010, 'desk'),
      A: wide(67030, 'canteen'),
      I: wide(67075, 'tuckshop'),
      k: box(67038, 'tuckshop', 3),
      J: box(67138, 'vending', 2, { lock: 'pry' }),
      l: box(67031, 'locker'),
      p: box(67040, 'bag'),
      b: box(67063, 'gym'),
      j: box(67139, 'sundries', 2, { lock: 'pry' }),
      t: box(67084, 'trash', 1),
      n: wide(67083, 'camp'),
    },
    rooms: [
      { id: 'office', x: 1, y: 1, w: 8, h: 5, label: { en: 'Office', zh: '办公室' } },
      { id: 'bath-infirmary', x: 10, y: 1, w: 7, h: 5, label: { en: 'Infirmary', zh: '医务室' } },
      { id: 'lab', x: 18, y: 1, w: 9, h: 5, label: { en: 'Science Lab', zh: '实验室' } },
      { id: 'corridor', x: 1, y: 7, w: 26, h: 1, label: { en: 'Upper Corridor', zh: '二层走廊' } },
      { id: 'classA', x: 1, y: 9, w: 5, h: 5, label: { en: 'Classroom 1-A', zh: '一年级A班' } },
      { id: 'classB', x: 7, y: 9, w: 5, h: 5, label: { en: 'Classroom 1-B', zh: '一年级B班' } },
      { id: 'stairs', x: 13, y: 9, w: 1, h: 5, label: { en: 'Stairwell', zh: '楼梯间' } },
      { id: 'kitchen-canteen', x: 15, y: 9, w: 12, h: 5, label: { en: 'Canteen & Tuck Shop', zh: '食堂与小卖部' } },
      { id: 'hall', x: 1, y: 15, w: 26, h: 4, label: { en: 'Entrance Hall', zh: '门厅' } },
    ],
    lore: [9053, 9054, 9055, 9056],
    loreIn: ['l', 'C', 'Y', 'L', 'F', 'O', 'B'],
  },
  {
    id: 'hospital',
    icon: '🏥',
    name: { en: 'Abandoned Hospital', zh: '废弃医院' },
    desc: {
      en: 'Dark wards, sealed pharmacy cabinets and electrical boxes. Medicine is plentiful, and so are the dead. Someone left records here — and an old recorder.',
      zh: '漆黑的病房、封存的药柜和配电箱。药品很多，丧尸也很多。有人在这里留下了病历——还有一台老式记录仪。',
    },
    size: 'large',
    tier: 3,
    unlockDay: [24, 28],
    hours: [6, 20],
    danger: 1.3,
    dark: true,
    richness: 1.2,
    travelMin: 60,
    zombies: 6,
    bigChance: 0.15,
    mapPos: [0.16, 0.72],
    map: [
      '########################',
      '#YY..FF.#E...E#S.RR.RR.#',
      '#.......#..G..#........#',
      '#K......#.....#...z...m#',
      '#......F#E...E#B.....C.#',
      '#.......#.....#........#',
      '####.######.######.#####',
      '#.........z........II..#',
      '###########.############',
      '#.TT......#.#.LL..VV...#',
      '#.....z...#X#......z...#',
      '#M........#.#Q........C#',
      '#......rr.#.#...U......#',
      '#####.#####.######.#####',
      '#H.......NN..NN.......A#',
      '#....z.............z...#',
      '#..P................O..#',
      '###########D############',
    ],
    legend: {
      Y: wide(66015, 'filing', 2, { id: 'papers', recipe: RATION_PRESS_RECIPE }),
      F: box(66136, 'filing'),
      E: box(66070, 'electrical', 2, { lock: 'pry' }),
      S: box(66126, 'sealedMeds', 2, { lock: 'pry' }),
      R: wide(66020, 'medicine'),
      G: box(66062, 'generator', 2, { lock: 'pry' }),
      K: box(66133, 'filing', 1, { id: 'recorderCabinet', story: [{ item: ITEM.recorder }] }),
      m: box(66013, 'medicine', 2, { id: 'pharmacyCabinet', story: [{ item: 9043 }] }),
      B: box(66026, 'medicine'),
      C: box(66114, 'medFridge', 2, { lock: 'pry' }),
      I: wide(66030, 'nurse', 2, { id: 'wardDesk', story: [{ item: 9064, cond: 'student' }] }),
      T: wide(66012, 'nurse', 2, { id: 'outpatientDesk', story: [{ item: 9041 }] }),
      L: wide(66011, 'lab', 2, { id: 'labBench', story: [{ item: 9042 }] }),
      V: box(66009, 'lab', 1),
      X: block(66007),
      M: box(66122, 'medicine'),
      Q: box(66022, 'lab'),
      r: rest(9122),
      U: box(66016, 'medWaste'),
      H: box(66023, 'medWaste', 1),
      N: wide(66027, 'nurse'),
      A: box(66097, 'medicine'),
      P: box(66192, 'bag', 2, { id: 'patientBag', story: [{ item: 9063, cond: 'student' }] }),
      O: box(66144, 'stockroom'),
    },
    rooms: [
      { id: 'records', x: 1, y: 1, w: 7, h: 5, label: { en: 'Records Room', zh: '病案室' } },
      { id: 'electrical', x: 9, y: 1, w: 5, h: 5, label: { en: 'Electrical Room', zh: '配电室' } },
      { id: 'bath-pharmacy', x: 15, y: 1, w: 8, h: 5, label: { en: 'Pharmacy', zh: '药房' } },
      { id: 'corridor', x: 1, y: 7, w: 22, h: 1, label: { en: 'Upper Corridor', zh: '楼上走廊' } },
      { id: 'bath-outpatient', x: 1, y: 9, w: 9, h: 4, label: { en: 'Outpatient Clinic', zh: '门诊' } },
      { id: 'passage', x: 11, y: 9, w: 1, h: 4, label: { en: 'Stairwell', zh: '楼梯间' } },
      { id: 'bath-lab', x: 13, y: 9, w: 10, h: 4, label: { en: 'Laboratory', zh: '检验科' } },
      { id: 'lobby', x: 1, y: 14, w: 22, h: 3, label: { en: 'Lobby & Nurse Station', zh: '大厅与护士站' } },
    ],
  },
  {
    id: 'office',
    icon: '🏢',
    name: { en: 'Office Ruins', zh: '办公废墟' },
    desc: {
      en: 'A gutted office tower of the company whose logo keeps turning up in the clues. Server rooms, an archive and an executive suite behind barricades. Rich pickings, heavy traffic.',
      zh: '一栋被掏空的写字楼，线索里反复出现的那家公司就在这里办公。机房、档案室和路障后的高管办公室。收获丰厚，丧尸也多。',
    },
    size: 'large',
    tier: 4,
    unlockDay: [38, 42],
    hours: [8, 18],
    danger: 1.45,
    dark: false,
    richness: 1.3,
    travelMin: 60,
    zombies: 7,
    bigChance: 0.2,
    mapPos: [0.86, 0.5],
    map: [
      '########################',
      '#P...E.#FF..a.F#BB....S#',
      '#G.....#...z...#...O...#',
      '#.....T#N......#rr.....#',
      '#......#.......#.......#',
      '###.#######.#######X####',
      '#......z..............H#',
      '########X###############',
      '#.K..K....K..K..#U..Y.V#',
      '#......z........#......#',
      '#F....................z#',
      '#.K..K....K..K..#.....Q#',
      '#..............L#......#',
      '######.#####.###########',
      '#p.......CC...........p#',
      '#.....z...........z....#',
      '#...b..............t...#',
      '############D###########',
    ],
    legend: {
      P: box(67004, 'electrical', 3, { lock: 'pry' }),
      E: box(67001, 'electrical', 2, { lock: 'pry' }),
      F: box(67187, 'filing'),
      a: box(67053, 'filing', 2, { id: 'archiveCabinet', story: [{ item: 9062 }] }),
      B: wide(67162, 'bookcase', 3),
      S: box(67171, 'safe', 2, { lock: 'pick' }),
      G: box(67003, 'generator', 2, { lock: 'pry' }),
      O: box(66154, 'office'),
      T: box(66161, 'toolCabinet'),
      N: box(66034, 'office'),
      r: rest(42038),
      X: block(66055),
      H: box(66109, 'fireCabinet', 1),
      K: box(67010, 'desk'),
      U: box(66113, 'fridge'),
      Y: box(67148, 'vending', 1),
      V: box(67136, 'vending', 2, { lock: 'pry' }),
      Q: box(67160, 'breakroom'),
      L: box(66162, 'stockroom'),
      C: wide(67128, 'office'),
      p: box(67158, 'plant', 1),
      b: box(66192, 'bag'),
      t: box(66188, 'trash', 1),
    },
    rooms: [
      { id: 'server', x: 1, y: 1, w: 6, h: 4, label: { en: 'Server Room', zh: '机房' } },
      { id: 'archive', x: 8, y: 1, w: 7, h: 4, label: { en: 'Archive', zh: '档案室' } },
      { id: 'exec', x: 16, y: 1, w: 7, h: 4, label: { en: 'Executive Suite', zh: '高管办公室' } },
      { id: 'corridor', x: 1, y: 6, w: 22, h: 1, label: { en: 'Service Corridor', zh: '后勤走廊' } },
      { id: 'open', x: 1, y: 8, w: 15, h: 5, label: { en: 'Open-Plan Office', zh: '开放办公区' } },
      { id: 'kitchen-break', x: 17, y: 8, w: 6, h: 5, label: { en: 'Break Room', zh: '茶水间' } },
      { id: 'lobby', x: 1, y: 14, w: 22, h: 3, label: { en: 'Lobby', zh: '大堂' } },
    ],
    lore: [9057, 9058, 9059, 9060, 9061],
    loreIn: ['F', 'O', 'N', 'T', 'S', 'K', 'Q'],
  },
].map(withWing);

export const SITE_BY_ID = Object.fromEntries(SITES.map((s) => [s.id, s]));

export const EXPOSURE_LEVELS = [
  { min: 0, id: 'quiet', label: { en: 'Quiet', zh: '安静' } },
  { min: 30, id: 'noticed', label: { en: 'Noticed', zh: '被察觉' } },
  { min: 60, id: 'hunted', label: { en: 'Hunted', zh: '被盯上' } },
  { min: 90, id: 'horde', label: { en: 'Swarmed', zh: '尸群围拢' } },
];
