// UI strings in English and Simplified Chinese.
export const STRINGS = {
  'game.title': { en: 'Survival Log', zh: '生存日志' },
  'game.tagline': {
    en: 'The apocalypse is coming in 10 hours. This time, you are ready.',
    zh: '末日将在10小时后降临。这一次，你早有准备。',
  },
  'menu.continue': { en: 'Continue', zh: '继续游戏' },
  'menu.new': { en: 'New Game', zh: '新游戏' },
  'menu.load': { en: 'Load', zh: '读取存档' },
  'menu.endless': { en: 'Endless Mode', zh: '无尽模式' },
  'menu.codex': { en: 'Codex', zh: '图鉴' },
  'menu.achievements': { en: 'Achievements', zh: '成就' },
  'menu.settings': { en: 'Settings', zh: '设置' },
  'menu.updateLog': { en: 'Update Log', zh: '更新日志' },
  'menu.profile': { en: 'Survivor Profile', zh: '幸存者档案' },
  'menu.back': { en: 'Back', zh: '返回' },
  'menu.start': { en: 'Start', zh: '开始' },
  'menu.resume': { en: 'Resume', zh: '继续' },
  'menu.saveQuit': { en: 'Save & Quit to Menu', zh: '保存并返回主菜单' },
  'menu.save': { en: 'Save', zh: '保存' },
  'menu.paused': { en: 'Paused', zh: '已暂停' },
  'menu.report': { en: 'Report an Issue (F7)', zh: '反馈问题 (F7)' },
  'menu.skipPrologue': { en: 'Skip prologue', zh: '跳过序章' },
  'menu.difficulty': { en: 'Difficulty', zh: '难度' },
  'menu.custom': { en: 'Custom', zh: '自定义' },
  'menu.chooseCharacter': { en: 'Choose your past', zh: '选择你的身份' },
  'menu.locked': { en: 'Locked', zh: '未解锁' },
  'menu.noSaves': { en: 'No saves yet.', zh: '暂无存档。' },
  'menu.delete': { en: 'Delete', zh: '删除' },
  'menu.confirm': { en: 'Confirm', zh: '确认' },
  'menu.cancel': { en: 'Cancel', zh: '取消' },
  'menu.close': { en: 'Close', zh: '关闭' },

  'stat.sat': { en: 'Satiety', zh: '饱腹' },
  'stat.sta': { en: 'Stamina', zh: '精力' },
  'stat.mor': { en: 'Morale', zh: '心态' },
  'stat.life': { en: 'Life', zh: '生命' },
  'stat.money': { en: 'Money', zh: '资金' },
  'stat.points': { en: 'Planning Points', zh: '生存点' },
  'stat.weight': { en: 'Carry', zh: '负重' },

  'time.day': { en: 'Day {n}', zh: '第{n}天' },
  'time.untilOutbreak': { en: 'Outbreak in', zh: '灾变倒计时' },
  'time.paused': { en: 'Paused', zh: '暂停' },
  'time.relaxed': { en: 'Relaxed', zh: '悠闲' },

  'phase.pre': { en: 'Before the Disaster', zh: '灾变前' },
  'phase.post': { en: 'After the Disaster', zh: '灾变后' },

  'ui.inventory': { en: 'Backpack', zh: '背包' },
  'ui.phone': { en: 'Phone', zh: '手机' },
  'ui.map': { en: 'Map', zh: '地图' },
  'ui.log': { en: 'Survival Log', zh: '生存日志' },
  'ui.planning': { en: 'Planning Mode', zh: '规划模式' },
  'ui.power': { en: 'Power', zh: '电力' },
  'ui.search': { en: 'Find Supplies', zh: '物资查找' },
  'ui.objectives': { en: 'Objectives', zh: '事件' },
  'ui.suggestions': { en: 'Suggestions', zh: '行动建议' },
  'ui.take': { en: 'Take', zh: '取用' },
  'ui.takeAll': { en: 'Take All (E)', zh: '全部拿取 (E)' },
  'ui.drop': { en: 'Drop (Q)', zh: '丢弃 (Q)' },
  'ui.use': { en: 'Use', zh: '使用' },
  'ui.eat': { en: 'Eat', zh: '食用' },
  'ui.read': { en: 'Read', zh: '阅读' },
  'ui.open': { en: 'Open', zh: '打开' },
  'ui.cut': { en: 'Cut Up', zh: '切分' },
  'ui.buy': { en: 'Buy', zh: '购买' },
  'ui.sell': { en: 'Sell', zh: '出售' },
  'ui.return': { en: 'Return', zh: '退货' },
  'ui.install': { en: 'Install', zh: '安装' },
  'ui.dismantle': { en: 'Dismantle', zh: '拆除' },
  'ui.move': { en: 'Move', zh: '移动' },
  'ui.finishPrep': { en: 'Finish Preparation', zh: '完成准备' },
  'ui.travel': { en: 'Travel', zh: '前往' },
  'ui.home': { en: 'Home', zh: '家' },
  'ui.weight': { en: '{kg} kg', zh: '{kg}千克' },
  'ui.full': { en: 'Not enough space', zh: '空间不足' },
  'ui.tooHeavy': { en: 'Too heavy', zh: '太重了' },
  'ui.notEnoughMoney': { en: 'Not enough money', zh: '资金不足' },
  'ui.expiring': { en: 'Expiring soon', zh: '即将过期' },
  'ui.expired': { en: 'Expired', zh: '已过期' },
  'ui.spoiled': { en: 'Spoiled', zh: '已腐坏' },
  'ui.servings': { en: '{n} servings left', zh: '剩余{n}份' },
  'ui.days': { en: '{n} d', zh: '{n}天' },
  'ui.hours': { en: '{n} h', zh: '{n}小时' },
  'ui.minutes': { en: '{n} min', zh: '{n}分钟' },
  'ui.craft': { en: 'Craft', zh: '制造' },
  'ui.craftAgain': { en: 'Craft Again', zh: '再次制造' },
  'ui.cook': { en: 'Cook', zh: '烹饪' },
  'ui.collect': { en: 'Collect', zh: '收取' },
  'ui.clear': { en: 'Clear', zh: '清空' },
  'ui.organize': { en: 'One-Click Organize', zh: '一键整理' },
  'ui.cancelAction': { en: 'Cancel', zh: '取消' },
  'ui.queue': { en: 'Action queue', zh: '行动队列' },
  'ui.none': { en: 'None', zh: '无' },
  'ui.setTrap': { en: 'Set Trap', zh: '布置' },
  'ui.dailyLimit': { en: 'Done for today', zh: '今日已达上限' },
  'wish.fulfilled': { en: 'Wish fulfilled! +15 Morale, +10 Planning Points', zh: '愿望达成！心态+15，生存点+10' },
};
