// @ts-check
// Aggregates balance sessions into the numbers docs/BALANCE.md bands, and writes the report (docs/balance/P<n>.md).
import { DIFFICULTIES, SAT_PER_DAY, evaluateBands } from './bands.mjs';
import { BOTS } from './bots.mjs';
import { FOOD_DAYS, MILESTONES, pct, summarize } from './summary.mjs';
export { MILESTONES, SAT_PER_DAY, pct, summarize };

/** @typedef {import('./session.mjs').SessionResult} SessionResult */

/**
 * @param {SessionResult[]} sessions
 * @param {string} [phase]  the phase whose bands must hold
 */
export function aggregate(sessions, phase = 'P0') {
  /** @type {Record<string, Record<string, import('./summary.mjs').Summary>>} */
  const by = {};
  const order = Object.keys(BOTS);
  for (const bot of [...new Set(sessions.map((s) => s.bot))].sort((x, y) => order.indexOf(x) - order.indexOf(y))) {
    by[bot] = {};
    for (const d of DIFFICULTIES) {
      const runs = sessions.filter((s) => s.bot === bot && s.difficulty === d);
      if (runs.length) by[bot][d] = summarize(runs);
    }
  }
  const bands = evaluateBands(by, phase);
  const crashes = sessions.filter((s) => s.end === 'crash');
  const trips = sessions.flatMap((s) => s.roundTrips.map((t) => ({ ...t, bot: s.bot, difficulty: s.difficulty, seed: s.seed })));
  const unchecked = sessions.filter((s) => !s.roundTrips.length && s.end !== 'crash');
  return { by, bands, crashes, roundTrips: { checked: trips.length, ok: trips.filter((t) => t.ok).length, failed: trips.filter((t) => !t.ok), unchecked } };
}

/** @param {number} v */
const f0 = (v) => (Number.isFinite(v) ? String(Math.round(v)) : '—');
/** @param {number} v */
const f1 = (v) => (Number.isFinite(v) ? v.toFixed(1) : '—');
/** @param {number} v */
const pc = (v) => (Number.isFinite(v) ? `${Math.round(v * 100)} %` : '—');
const DNAME = /** @type {Record<string, string>} */ ({ relaxed: 'Relaxed', normal: 'Normal', hard: 'Hard', outOfAmmo: 'Out of Ammo and Food' });

/**
 * @param {ReturnType<typeof aggregate>} agg
 * @param {{ phase: string, command: string, when: string, where: string, sessions: number, workers: number, secs: number, seeds: number, days: number }} meta
 */
export function markdown(agg, meta) {
  const L = [];
  L.push(`# Balance report — ${meta.phase}`, '');
  L.push(
    `Generated by \`${meta.command}\` on ${meta.when} at ${meta.where}: ${meta.sessions} sessions (${Object.keys(agg.by).length} bots × ${DIFFICULTIES.length} difficulties × ${meta.seeds} seeds, one for a bot whose outcome does not depend on the seed, up to Day ${meta.days}) of the real sim, each in a fresh worker thread, ${meta.workers} at a time, ${meta.secs.toFixed(0)} s. The bots, the metrics and the bands are [docs/BALANCE.md](../BALANCE.md); every number below is measured, none is taken from a table.`,
    ''
  );
  L.push('## Release checks', '', '| check | result |', '| --- | --- |');
  L.push(`| crashes (docs/QUALITY.md: zero over 200 bot sessions) | ${agg.crashes.length} in ${meta.sessions} sessions |`);
  L.push(`| save/load round trips (100 %) | ${agg.roundTrips.ok} of ${agg.roundTrips.checked} identical after 24 h, in ${meta.sessions - agg.roundTrips.unchecked.length} of ${meta.sessions} sessions |`);
  L.push('');
  if (agg.crashes.length) {
    L.push('Crashes:', '');
    for (const c of agg.crashes.slice(0, 10)) L.push(`- ${c.bot} ${c.difficulty} seed ${c.seed}: \`${(c.crash || '').split('\n')[0]}\``);
    L.push('');
  }
  if (agg.roundTrips.failed.length) {
    L.push('Round trips that differ:', '');
    for (const r of agg.roundTrips.failed.slice(0, 10)) L.push(`- ${r.bot} ${r.difficulty} seed ${r.seed}, ${r.at}: ${r.detail}`);
    L.push('');
  }
  const req = agg.bands.filter((b) => b.required);
  const held = req.filter((b) => b.state === 'inside').length;
  L.push('## Bands', '', `${held} of ${req.length} bands this phase requires hold; ${req.length - held} fail (outside or unmeasured). Bands of later phases are listed for the bots that will play them.`, '');
  L.push('| band | from | band | measured | | evidence |', '| --- | --- | --- | ---: | --- | --- |');
  const num = (/** @type {number} */ v) => (Math.abs(v) >= 10 || Number.isInteger(v) ? String(Math.round(v * 10) / 10) : v.toFixed(2));
  for (const b of agg.bands) {
    const range = `${num(b.min)} – ${b.max === Infinity ? '∞' : num(b.max)}`;
    const mark = !b.required ? `not required before ${b.from}` : b.state === 'inside' ? '✔' : b.state === 'outside' ? '✖ outside' : '✖ unmeasured';
    L.push(`| \`${b.id}\`: ${b.what} | ${b.from} | ${range} | ${b.value == null ? '—' : num(b.value)} (${b.detail}) | ${mark} | ${b.source} |`);
  }
  L.push('');
  for (const [bot, byD] of Object.entries(agg.by)) {
    L.push(`## ${bot}: ${/** @type {any} */ (BOTS)[bot]?.title || bot}`, '');
    L.push('### Days survived', '', `| difficulty | runs | min | p10 | median | p90 | max | alive on Day ${MILESTONES.join(' / ')} |`, '| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |');
    for (const [d, s] of Object.entries(byD)) L.push(`| ${DNAME[d]} | ${s.n} | ${s.days.min} | ${s.days.p10} | ${s.days.median} | ${s.days.p90} | ${s.days.max} | ${MILESTONES.map((m) => pc(s.alive[m])).join(' / ')} |`);
    const causes = [...new Set(Object.values(byD).flatMap((s) => Object.keys(s.causes)))].sort();
    L.push('', '### Deaths by cause', '', `| difficulty | deaths | ${causes.join(' | ')} |`, `| --- | ---: | ${causes.map(() => '---:').join(' | ')} |`);
    for (const [d, s] of Object.entries(byD)) L.push(`| ${DNAME[d]} | ${s.deaths} | ${causes.map((c) => (s.causes[c] ? `${s.causes[c]} (${pc(s.causes[c] / s.deaths)})` : '0')).join(' | ')} |`);
    L.push('', '### Food at home', '', 'Median satiety of the food in the backpack and home storage each morning, in days of eating (÷ 40), over the runs alive that day.', '');
    L.push(`| difficulty | ${FOOD_DAYS.map((d) => `Day ${d}`).join(' | ')} |`, `| --- | ${FOOD_DAYS.map(() => '---:').join(' | ')} |`);
    for (const [d, s] of Object.entries(byD)) L.push(`| ${DNAME[d]} | ${FOOD_DAYS.map((x) => f1(s.food[x])).join(' | ')} |`);
    const hordeDays = MILESTONES.filter((m) => m < 100 && Object.values(byD).some((s) => s.hordes[m]?.faced));
    if (hordeDays.length) {
      L.push('', '### Hordes', '', 'Survived / faced, and how many of those broke a door or window, for each horde of the story schedule.', '');
      L.push(`| difficulty | ${hordeDays.map((d) => `Day ${d}`).join(' | ')} |`, `| --- | ${hordeDays.map(() => '---').join(' | ')} |`);
      for (const [d, s] of Object.entries(byD)) L.push(`| ${DNAME[d]} | ${hordeDays.map((m) => (s.hordes[m]?.faced ? `${s.hordes[m].survived}/${s.hordes[m].faced}${s.hordes[m].breached ? ` (${s.hordes[m].breached} breached)` : ''}` : '—')).join(' | ')} |`);
    }
    L.push('', '### Planning points per loop', '', '| difficulty | p10 | median | p90 |', '| --- | ---: | ---: | ---: |');
    for (const [d, s] of Object.entries(byD)) L.push(`| ${DNAME[d]} | ${f0(s.points.p10)} | ${f0(s.points.median)} | ${f0(s.points.p90)} |`);
    L.push('');
  }
  return `${L.join('\n')}\n`;
}
