#!/usr/bin/env python3
"""Build the browser game's data modules from the extracted Survival Log config.

Input:  research/datavw/survival_log_codex.sqlite3 (SurvivalLogDataViewer snapshot of the
        game's MemoryPack config, game version 1.0.15704) and its achievement_conditions.json.
        Optional English names: tools/i18n/en.json ({"<zh string>": "<english>"}).
Output: src/data/gen/*.js ES modules (checked in, so the game runs without Python).

Run:    python3 tools/build_data.py
"""
from __future__ import annotations

import json
import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "research" / "datavw" / "survival_log_codex.sqlite3"
ACH_JSON = ROOT / "research" / "datavw" / "achievement_conditions.json"
STEAM_ACH = ROOT / "research" / "achievements.txt"
EN_JSON = ROOT / "tools" / "i18n" / "en.json"
OUT = ROOT / "src" / "data" / "gen"

ZW = re.compile(r"[\u200b\u200c\u200d\ufeff]")


def clean(s):
    if not isinstance(s, str):
        return s
    return ZW.sub("", s).replace("\\n", "\n").strip()


def load(cur, sql, args=()):
    return [json.loads(r[0]) for r in cur.execute(sql, args)]


def write_module(name: str, export: str, payload, header: str = ""):
    OUT.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    text = (
        "// Generated by tools/build_data.py from the extracted Survival Log config. Do not edit.\n"
        + (header + "\n" if header else "")
        + f"export const {export} = {body};\n"
    )
    (OUT / f"{name}.js").write_text(text, encoding="utf-8")
    return len(text)


def main():
    if not DB.exists():
        sys.exit(f"missing {DB}; clone https://github.com/tianwaiyan/SurvivalLogDataViewer into research/datavw")
    con = sqlite3.connect(DB)
    cur = con.cursor()

    # ---------------------------------------------------------------- items
    items = {}
    for d in load(cur, "select raw_json from recipe_items order by item_id"):
        items[d["ID"]] = {
            "id": d["ID"],
            "zh": clean(d.get("ItemName_Local", "")),
            "d1": clean(d.get("ItemDes1_Local", "")),
            "d2": clean(d.get("ItemDes2_Local", "")),
            "cat": d["Category"],
            "sub": d["SubCategory"],
            "cook": bool(d.get("CanCook")),
            "tags": [t for t in (d.get("FoodTag1", 0), d.get("FoodTag2", 0), d.get("FoodTag3", 0)) if t],
            "size": d.get("Size", [1, 1]),
            "price": d.get("price", 0),
            "g": d.get("weight", 0),
            "life": d.get("Life", -1),
            "rotT": d.get("IT_Rot_Threshold", 0),
            "rot": d.get("It_Rot_Product_Id", []),
            "uses": d.get("UseTimes", 1),
            "sat": d.get("ValueDisplay1", 0),
            "mor": d.get("ValueDisplay2", 0),
            "sta": d.get("ValueDisplay3", 0),
            "v4": d.get("ValueDisplay4", 0),
            "hp": d.get("ValueDisplay5", 0),
            "stack": d.get("StackLimit", 1),
            "taste": d.get("Taste", 0),
            "wish": d.get("WishPower", 0),
            "story": d.get("Story", 0),
            "daily": d.get("DailyMax", 0),
            "plant": d.get("Plant", 0),
            "plantFast": d.get("Plant_Fast", 0),
            "burn": d.get("BurnValue", 0) if d.get("Burnable") else 0,
            "trap": d.get("Trap", 0),
            "furn": d.get("TargetFurnitureID", 0),
            "prey": d.get("Prey_Rarity", 0),
            "discExp": d.get("IT_Discovery_Exp", 0),
            "capExp": d.get("CaptureExp", 0),
            "trade": d.get("TradeValue", 0),
            "rec": d.get("RecommendType", 0),
            "codex": bool(d.get("InCodex")),
            "brew": bool(d.get("CanBrew")),
            "cut": d.get("CutProductId", 0),
            "noUse": bool(d.get("CantUse")),
            "peace": bool(d.get("CanUsePeace")),
            "od": d.get("OverdueDebuff", []),
            "odPow": d.get("DebuffPow", []),
            "cond": d.get("ConditionSetId", 0),
            "demand": bool(d.get("IsHighDemand")),
            "vaseLife": d.get("VaseLife", 0),
            "vaseMor": d.get("VaseMoraleRate", 0),
        }

    # ---------------------------------------------------------------- cooking recipes
    recipes = {}
    for d in load(cur, "select raw_json from codex_entries where source_table='Config_CookingRecipe' order by source_id"):
        recipes[d["ID"]] = {
            "id": d["ID"],
            "zh": clean(d.get("RecipeName_Local", "")),
            "tags": d.get("TagCombo", []),
            "items": d.get("SpecificItems", []),
            "out": [d.get("PerfectItemID"), d.get("GoodItemID"), d.get("NormalItemID"), d.get("FailItemID")],
            "tier": d.get("Tier", 0),
            "q": d.get("QualityMap", [0, 0, 0, 0]),
            "minLv": d.get("MinLevel", 0),
            "time": d.get("CookTime", 0),
            "satStd": d.get("SatietyStandard", 0),
            "exp": d.get("CookExp", 0),
            "showLv": d.get("ShowLevel", 0),
            "craftLv": d.get("CraftLevel", 0),
            "discExp": d.get("DiscoveryExp", 0),
        }
    tier_rules = [
        {"sub": r[0], "label": r[1], "high": r[2], "midLow": r[3]}
        for r in cur.execute("select sub_category,label,high_threshold,mid_low_threshold from recipe_tier_rules")
    ]

    # ---------------------------------------------------------------- plants
    plants = {}
    for d in load(cur, "select raw_json from codex_entries where source_table='Config_Plant' order by source_id"):
        plants[d["ID"]] = {
            "id": d["ID"],
            "zh": clean(d.get("Name_Local", "")),
            "desc": clean(d.get("Des_Local", "")),
            "size": d.get("Size", 1),
            "grow": d.get("GrowthTime", 0),
            "light": d.get("LightNeed", 0),
            "cold": d.get("ColdResistance", 0),
            "pest": d.get("Pest", 0),
            "weed": d.get("Weed", 0),
            "dry": d.get("Dry", 0),
            "gain": d.get("Gain", []),
            "hExp": d.get("HarvestExp", 0),
            "pGain": d.get("Perfect_Gain", []),
            "pRate": d.get("Perfect_Rate", 0),
            "seed": d.get("Gain_Seed", []),
            "seedRate": d.get("Seed_Rate", 0),
            "wither": d.get("WitheredGain", []),
            "decay": d.get("DecayTime", 0),
            "window": d.get("HarvestTime", 0),
            "discExp": d.get("Discovery_Exp", 0),
            "codex": bool(d.get("InCodex")),
        }

    # ---------------------------------------------------------------- crafting
    crafts = {}
    for d in load(cur, "select raw_json from codex_entries where source_table='Config_ProductionList' order by source_id"):
        crafts[d["ID"]] = {
            "id": d["ID"],
            "zh": clean(d.get("ShopName_Local", "")),
            "mat": d.get("MaterialList", []),
            "out": d.get("ProductID", []),
            "fail": d.get("FailedID", []),
            "lv": d.get("Level", 1),
            "use": bool(d.get("IsUseable", True)),
            "lifeMin": d.get("LifeMin", 0),
            "showLv": d.get("show_level", 0),
            "craftLv": d.get("craft_level", 0),
            "pOut": d.get("perfect_item_id", []),
            "pRate": d.get("perfect_rate", 0),
            "discExp": d.get("discovery_exp", 0),
            "codex": bool(d.get("InCodex")),
            "note": d.get("NoteCategory", 0),
            "defExp": d.get("defense_exp", 0),
            "discount": d.get("DiscountRate", 1),
            "demo": d.get("DemoTwoMode", 0),
        }

    # ---------------------------------------------------------------- furniture
    furniture = {}
    for d in load(cur, "select raw_json from codex_entries where source_table='Config_Furniture' order by source_id"):
        furniture[d["ID"]] = {
            "id": d["ID"],
            "zh": clean(d.get("Name_Local", "")),
            "desc": clean(d.get("Des_Local", "")),
            "res": d.get("ResName", ""),
            "price": d.get("FurniturePrice", 0),
            "pawn": d.get("PawnPrice", 0),
            "inst": d.get("InstallTime", 0),
            "type": d.get("FurnitureType", 0),
            "page": d.get("ShopPage", 0),
            "slot": d.get("SlotType", 0),
            "store": d.get("ShowStorage", 0),
            "hp": d.get("FurnitureHPMax", 0),
            "funcs": d.get("FurnitureFunc", []),
            "rmFunc": d.get("RemoveFunc", []),
            "mvFunc": d.get("MoveFunc", []),
            "rmGet": d.get("RemoveGet", []),
            "plant": d.get("PlantFurnitureID", 0),
            "cook": d.get("CookFurnitureID", 0),
            "vase": d.get("VaseCapacity", 0),
            "bag": d.get("BagId", 0),
            "elec": d.get("ElectricalType", 0) if d.get("IsElectrical") or d.get("ElectricalType") else 0,
            "cold": d.get("ColdRate", 0),
            "pw": d.get("PowerCost", 0),
            "pwMode": d.get("PowerMode", 0),
            "heat": d.get("HeatOutput", 0),
            "elecCfg": d.get("ElectricalFurnitureID", 0),
            "restore": d.get("RestoreCoeff", 0),
            "defRed": d.get("DefReduceCoeff", 0),
            "codex": bool(d.get("InCodex")),
            "loot": d.get("LootRandomGroupId", 0),
            "lootN": d.get("LootRandomCount", 0),
            "story": d.get("Story", 0),
            "demo": d.get("DemoTwoMode", 0),
        }

    # ---------------------------------------------------------------- auxiliary tables
    aux = {}
    for (table,) in cur.execute("select distinct table_name from auxiliary_rows"):
        rows = []
        for (raw,) in con.execute("select raw_json from auxiliary_rows where table_name=? order by row_id", (table,)):
            d = json.loads(raw)
            d = {
                k: clean(v)
                for k, v in d.items()
                if not (isinstance(v, str) and ("Assets/" in v or "../../" in v or v.startswith("event:/")))
            }
            rows.append(d)
        aux[table.replace("Config_", "")] = rows

    funcs = {}
    for d in aux.pop("FurnitureFunc"):
        funcs[d["ID"]] = {
            "id": d["ID"],
            "zh": d.get("BtnName_Local", ""),
            "tip": d.get("BtnTips_Local", ""),
            "confirm": d.get("ConfirmInfo_Local", ""),
            "vis": d.get("VisibilityConditionSetId", 0),
            "cond": d.get("ConditionSetId", 0),
            "chapter": d.get("Chapter", 0),
            "cd": d.get("FunCD", 0),
            "daily": d.get("DailyMax", 0),
            "reward": d.get("RewardSetId", 0),
            "ftype": d.get("FuncType", 0),
            "acts": d.get("ActionIds", []),
            "jump": d.get("JumpMapId", 0),
            "preview": d.get("PreviewAttrDelta", ""),
            "group": d.get("GroupKey", ""),
        }

    # ---------------------------------------------------------------- codex membership
    codex = {}
    for entry_key, category, order in cur.execute(
        "select entry_key, category, sort_order from codex_entry_categories order by category, sort_order"
    ):
        table, sid = entry_key.split(":")
        codex.setdefault(category, []).append(int(sid))
    # The viewer's category table misses one InCodex blueprint (332, double-door fridge); the achievement
    # config counts 125 craft codex entries, so every InCodex production row belongs in the craft codex.
    for rid, r in sorted(crafts.items()):
        if r.get("codex") and rid not in codex.setdefault("craft", []):
            codex["craft"].append(rid)

    # ---------------------------------------------------------------- achievements
    steam = []
    if STEAM_ACH.exists():
        for line in STEAM_ACH.read_text(encoding="utf-8").splitlines():
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 3:
                steam.append({"en": parts[0], "desc": parts[1], "pct": parts[2]})
    cond = {}
    if ACH_JSON.exists():
        for a in json.loads(ACH_JSON.read_text(encoding="utf-8"))["achievements"]:
            cond[a["id"]] = a
    achievements = []
    for row in cur.execute(
        "select achievement_id, sort_order, name, description, category, is_hidden, raw_json from achievements order by sort_order"
    ):
        aid, order, name, desc, category, hidden, raw = row
        r = json.loads(raw)
        c = cond.get(aid, {})
        achievements.append(
            {
                "id": aid,
                "order": order,
                "zh": clean(name),
                "zhDesc": clean(desc),
                "cat": r.get("Category"),
                "catZh": category,
                "hidden": bool(hidden),
                "steam": r.get("SteamAPI", ""),
                "type": r.get("AchievementType"),
                "value": r.get("Value", []),
                "counter": r.get("CounterKey", ""),
                "threshold": r.get("Threshold", 0),
                "progressKey": r.get("ProgressCounterKey", ""),
                "progressTarget": r.get("ProgressTarget", 0),
                "condZh": c.get("condition", ""),
                "roleZh": c.get("role_restriction", ""),
                "notesZh": c.get("notes", []),
                "num": c.get("numeric_threshold"),
            }
        )

    # ---------------------------------------------------------------- english names
    en = {}
    if EN_JSON.exists():
        en = json.loads(EN_JSON.read_text(encoding="utf-8"))

    sizes = {}
    sizes["items"] = write_module("items", "ITEMS", items)
    sizes["recipes"] = write_module("recipes", "RECIPES", {"recipes": recipes, "tierRules": tier_rules})
    sizes["plants"] = write_module("plants", "PLANTS", plants)
    sizes["crafts"] = write_module("crafts", "CRAFTS", crafts)
    sizes["furniture"] = write_module("furniture", "FURNITURE", furniture)
    sizes["funcs"] = write_module("funcs", "FUNCS", funcs)
    sizes["aux"] = write_module("aux", "AUX", aux)
    sizes["codex"] = write_module("codex", "CODEX", codex)
    sizes["achievements"] = write_module("achievements", "ACHIEVEMENT_CONFIG", {"list": achievements, "steam": steam})
    sizes["en"] = write_module("en", "EN_NAMES", en)

    # strings that still need an English translation
    need = set()
    for d in items.values():
        need.add(d["zh"])
    for d in recipes.values():
        need.add(d["zh"])
    for d in plants.values():
        need.add(d["zh"])
    for d in crafts.values():
        need.add(d["zh"])
    for d in furniture.values():
        need.add(d["zh"])
    for d in funcs.values():
        need.add(d["zh"])
    for t in ("FoodType", "ItemSubCategory"):
        for d in aux.get(t, []):
            need.add(clean(d.get("Name_Local", "")))
    for d in aux.get("FurnitureTag", []):
        need.add(clean(d.get("TagName_Local", "")))
    need = sorted(s for s in need if s and s not in en)
    (ROOT / "tools" / "i18n").mkdir(parents=True, exist_ok=True)
    (ROOT / "tools" / "i18n" / "missing_names.json").write_text(
        json.dumps(need, ensure_ascii=False, indent=0), encoding="utf-8"
    )

    print("items", len(items), "recipes", len(recipes), "plants", len(plants), "crafts", len(crafts))
    print("furniture", len(furniture), "funcs", len(funcs), "achievements", len(achievements))
    print("codex", {k: len(v) for k, v in codex.items()})
    print("module bytes", sizes)
    print("names still missing English:", len(need))


if __name__ == "__main__":
    main()
